services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./db:/db
    environment:
      - PYTHONUNBUFFERED=1
    container_name: species-back
